### ISSUE TITLE
Vamos que tu puedes xD

### ISSUE THREAD

**Issue by kevinrobayna** [freinn/ilovecoding#1]
```js
    var a = "ABC";
    console.log(a);
    function func1(){
        var a = "DEF";
        console.log(a);
        function func2(){
            var a = "XYZ";
            console.log(a);
        }
        func2();
    }
    func1();
    console.log(a);
```
Ahí por suerte javascript respeta mas o menos el ambito xD aunque no tiene mucho sentido ya que se esta modificando el valor de a, peeeero como pones var a, el entiende que estas declarando una nueva variable en ves de darte un petardaso guapo (que es lo que debería darte).

Sabias que si en js pones 
```js 
a = 32
```
(y nunca nombras a "a" anteriormente) el interprete dice ah hostias que esta variable nunca a sido "declarada" será que el desarrollador se olvido de hacerlo bueno.. como no sé el ambito vamos a ponerla global xDDDDDDDD

```js
    a = "ABC";
    console.log(a);
    function func1(){
        a = "DEF";
        console.log(a);
        function func2(){
            a = "XYZ";
            console.log(a);
        }
        func2();
    }
    func1();
    console.log(a);
```

Buena suerte con js :smile:

**Comment by freinn** [comment]
jajajajja xD sí tío es que hoy en día no puedo permitirme no saber hacer
páginas web xDDDDD por eso me motivé y me puse, son 9 dólares al mes y así
me obligo a hacer el curso, porque lo estoy pagando xDDDD Es que quiero
montarme un par de páginas y aún no sé suficiente haskell para hacerlas en
haskell, así que de momento algo sencillito en javascript y a correr.

**Comment by kevinrobayna** [comment]
wow, ya me dices si merece la pena ;) Pero, mira lo que te pasé de django :)
